# Generated by Django 2.1.7 on 2019-04-30 08:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kursova', '0011_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='post',
            field=models.ForeignKey(default='def', on_delete=django.db.models.deletion.CASCADE, to='kursova.Post'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='poll',
            field=models.ForeignKey(default='def', on_delete=django.db.models.deletion.CASCADE, to='poll.Poll'),
        ),
    ]
