# Generated by Django 2.1.7 on 2019-04-30 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kursova', '0015_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='poll_link',
            field=models.TextField(null=True),
        ),
    ]
