# Generated by Django 2.1.7 on 2019-04-30 09:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kursova', '0020_post_poll_link'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='poll_link',
        ),
    ]
