# Generated by Django 2.1.7 on 2019-04-30 09:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kursova', '0023_auto_20190430_1249'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='poll_link',
        ),
    ]
