# Generated by Django 2.1.7 on 2019-05-05 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kursova', '0025_post_poll_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='poll_link',
            field=models.TextField(default='none'),
        ),
    ]
