# Generated by Django 2.1.7 on 2019-05-05 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kursova', '0029_auto_20190505_1421'),
    ]

    operations = [
        migrations.AlterField(
            model_name='images',
            name='slug',
            field=models.TextField(default='none'),
        ),
    ]
